services:
  db:
    image: postgres
    container_name: consult-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    container_name: consult-back
    restart: always
    build: .
    env_file:
      - .env.local
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db-data: